name: Front-End Build and Test

on:
  pull_request:
    branches:
      - develop
      - master
    paths:
      - "source/webui/**"
  push:
    branches:
      - develop
      - master
    paths:
      - "source/webui/**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
      working-directory: ./source/webui
    - name: Build front-end
      run: npm run build --if-present
      working-directory: ./source/webui
    #
    # Not implemented yet
    #
    # - name: Test front-end
    #   run: npm run build --if-present
    #   working-directory: ./src/frontend
